name: Create release

permissions:
  contents: write

on:
  release:
    types:
      - published
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install dependencies
        run: |
          npm ci
          composer install
          composer install --no-dev

      - name: Build assets
        run: npx mix --production

      - name: Create ZIP
        run: |
          zip -r acquired-com-for-woocommerce.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "node_modules/*" \
            -x "tests/*" \
            -x ".wordpress-org/*" \
            -x ".editorconfig" \
            -x ".distignore" \
            -x ".eslintrc.json" \
            -x ".gitattributes" \
            -x ".gitignore" \
            -x "CHANGELOG.md" \
            -x "composer.json" \
            -x "composer.lock" \
            -x "package.json" \
            -x "package-lock.json" \
            -x "patchwork.json" \
            -x "phpcs.xml" \
            -x "phpunit.xml" \
            -x "README.md" \
            -x "webpack.mix.js"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: acquired-com-for-woocommerce.zip
